### ISSUE TITLE
Can't activate the plugin

### ISSUE THREAD

**Issue by bubbastallcup** [johnellmore/wordpress-pco-api#1]
This is the error I get:

Warning: require_once(PlanningCenterOnline-API-Helper/PlanningCenterOnline.php): failed to open stream: No such file or directory in /hermes/waloraweb070/b324/moo.fbcmforg/2.0/wp-content/plugins/wordpress-pco-api-master/beltway-wp-pco.php on line 11 Fatal error: require_once(): Failed opening required 'PlanningCenterOnline-API-Helper/PlanningCenterOnline.php' (include_path='.:/usr/local/lib/php-5.3.13/lib/php') in /hermes/waloraweb070/b324/moo.fbcmforg/2.0/wp-content/plugins/wordpress-pco-api-master/beltway-wp-pco.php on line 11

**Comment by johnellmore** [comment]
@bubbastallcup -- Thanks for the report. That was due to using a library in a nested repository. I've moved the library to the root folder to make it simpler. Try downloading the most recent version and using it again.
