### ISSUE TITLE
Authentification

### ISSUE THREAD

**Issue by rom02b** [johnellmore/wordpress-pco-api#3]
Hi,

I'm not able to connect the account after the installation of the extension.
The plugin is activated, I field the ID and Secret number but when I click on Authentification I 'have a nothing (wp-admin/options-general.php?page=pco_connect&pco-action=auth)

Thanks for your help

**Comment by johnellmore** [comment]
@rom02b Unfortunately, this plugin was built a few years ago using Planning Center's old API (v1). The connection to that API has either been shut off or broken. Fixing this would require a rewrite of the API client library, as no drop-in replacement currently exists.

I've started work on a version of this plugin that will work with the current API version (v2). However, I can't give a concrete timeline for when that will ready, if ever.

I'm available to prioritize development of the new plugin version on a paid basis if you're interested.
